{
   "smileys":[
      {
         "filename":"allthethings.png",
         "textCodes":[
            "(allthethings)"
         ]
      },
      {
         "filename":"android.png",
         "textCodes":[
            "(android)"
         ]
      },
      {
         "filename":"angry.png",
         "textCodes":[
            ">:-("
         ]
      },
      {
         "filename":"areyoukiddingme.png",
         "textCodes":[
            "(areyoukiddingme)"
         ]
      },
      {
         "filename":"ashton.png",
         "textCodes":[
            "(ashton)"
         ]
      },
      {
         "filename":"atlassian.png",
         "textCodes":[
            "(atlassian)"
         ]
      },
      {
         "filename":"awthanks.png",
         "textCodes":[
            "(awthanks)"
         ]
      },
      {
         "filename":"awyea.png",
         "textCodes":[
            "(awyeah)"
         ]
      },
      {
         "filename":"badass.png",
         "textCodes":[
            "(badass)"
         ]
      },
      {
         "filename":"badjokeeel-1375463017.png",
         "textCodes":[
            "(badjokeeel)"
         ]
      },
      {
         "filename":"badpokerface.png",
         "textCodes":[
            "(badpokerface)"
         ]
      },
      {
         "filename":"basket.png",
         "textCodes":[
            "(basket)"
         ]
      },
      {
         "filename":"beer.png",
         "textCodes":[
            "(beer)"
         ]
      },
      {
         "filename":"bigsmile.png",
         "textCodes":[
            ":-D",
            ":D"
         ]
      },
      {
         "filename":"bitbucket-1349806629.png",
         "textCodes":[
            "(bitbucket)"
         ]
      },
      {
         "filename":"boom.gif",
         "textCodes":[
            "(boom)"
         ]
      },
      {
         "filename":"branch-1372171579.png",
         "textCodes":[
            "(branch)"
         ]
      },
      {
         "filename":"bumble.png",
         "textCodes":[
            "(bumble)"
         ]
      },
      {
         "filename":"bunny.png",
         "textCodes":[
            "(bunny)"
         ]
      },
      {
         "filename":"cadbury.png",
         "textCodes":[
            "(cadbury)"
         ]
      },
      {
         "filename":"cake.png",
         "textCodes":[
            "(cake)"
         ]
      },
      {
         "filename":"candycorn.png",
         "textCodes":[
            "(candycorn)"
         ]
      },
      {
         "filename":"caruso.png",
         "textCodes":[
            "(caruso)"
         ]
      },
      {
         "filename":"ceilingcat.png",
         "textCodes":[
            "(ceilingcat)"
         ]
      },
      {
         "filename":"cerealguy.png",
         "textCodes":[
            "(cereal)"
         ]
      },
      {
         "filename":"cerealspit-1349463282.png",
         "textCodes":[
            "(cerealspit)"
         ]
      },
      {
         "filename":"challengeaccepted.png",
         "textCodes":[
            "(challengeaccepted)"
         ]
      },
      {
         "filename":"chewy.png",
         "textCodes":[
            "(chewie)"
         ]
      },
      {
         "filename":"chocobunny.png",
         "textCodes":[
            "(chocobunny)"
         ]
      },
      {
         "filename":"chompy.gif",
         "textCodes":[
            "(chompy)"
         ]
      },
      {
         "filename":"chris.png",
         "textCodes":[
            "(chris)"
         ]
      },
      {
         "filename":"chucknorris-1342735388.png",
         "textCodes":[
            "(chucknorris)"
         ]
      },
      {
         "filename":"clarence-1369414730.png",
         "textCodes":[
            "(clarence)"
         ]
      },
      {
         "filename":"coffee.png",
         "textCodes":[
            "(coffee)"
         ]
      },
      {
         "filename":"confluence-1367948832.png",
         "textCodes":[
            "(confluence)"
         ]
      },
      {
         "filename":"content.png",
         "textCodes":[
            "(content)"
         ]
      },
      {
         "filename":"continue-1369948567.png",
         "textCodes":[
            "(continue)"
         ]
      },
      {
         "filename":"cool.png",
         "textCodes":[
            "8)",
            "8-)"
         ]
      },
      {
         "filename":"cornelius.png",
         "textCodes":[
            "(cornelius)"
         ]
      },
      {
         "filename":"cry.png",
         "textCodes":[
            ":'("
         ]
      },
      {
         "filename":"dance.gif",
         "textCodes":[
            "(dance)"
         ]
      },
      {
         "filename":"dealwithit.gif",
         "textCodes":[
            "(dealwithit)"
         ]
      },
      {
         "filename":"derp.png",
         "textCodes":[
            "(derp)"
         ]
      },
      {
         "filename":"disapproval.png",
         "textCodes":[
            "(disapproval)"
         ]
      },
      {
         "filename":"dosequis.png",
         "textCodes":[
            "(dosequis)"
         ]
      },
      {
         "filename":"drevil.png",
         "textCodes":[
            "(drevil)"
         ]
      },
      {
         "filename":"ducreux.png",
         "textCodes":[
            "(ducreux)"
         ]
      },
      {
         "filename":"dumbbitch.png",
         "textCodes":[
            "(dumb)"
         ]
      },
      {
         "filename":"embarrassed.png",
         "textCodes":[
            "(embarrassed)"
         ]
      },
      {
         "filename":"facepalm.png",
         "textCodes":[
            "(facepalm)"
         ]
      },
      {
         "filename":"failed-1369948578.png",
         "textCodes":[
            "(failed)"
         ]
      },
      {
         "filename":"fap.png",
         "textCodes":[
            "(fap)"
         ]
      },
      {
         "filename":"farnsworth.png",
         "textCodes":[
            "(goodnews)"
         ]
      },
      {
         "filename":"firstworldproblem-1342647915.png",
         "textCodes":[
            "(firstworldproblem)"
         ]
      },
      {
         "filename":"footinmouth.png",
         "textCodes":[
            ":#"
         ]
      },
      {
         "filename":"foreveralone.png",
         "textCodes":[
            "(foreveralone)"
         ]
      },
      {
         "filename":"freddie.png",
         "textCodes":[
            "(freddie)"
         ]
      },
      {
         "filename":"frown.png",
         "textCodes":[
            ":("
         ]
      },
      {
         "filename":"fry.png",
         "textCodes":[
            "(fry)"
         ]
      },
      {
         "filename":"fuckyeah.png",
         "textCodes":[
            "(fuckyeah)"
         ]
      },
      {
         "filename":"fwp-1342647892.png",
         "textCodes":[
            "(fwp)"
         ]
      },
      {
         "filename":"gangnamstyle-1349387710.gif",
         "textCodes":[
            "(gangnamstyle)"
         ]
      },
      {
         "filename":"garret.png",
         "textCodes":[
            "(garret)"
         ]
      },
      {
         "filename":"gasp.png",
         "textCodes":[
            ":o"
         ]
      },
      {
         "filename":"gates.png",
         "textCodes":[
            "(gates)"
         ]
      },
      {
         "filename":"ghost.png",
         "textCodes":[
            "(ghost)"
         ]
      },
      {
         "filename":"greenbeer.png",
         "textCodes":[
            "(greenbeer)"
         ]
      },
      {
         "filename":"grumpycat-1366734534.png",
         "textCodes":[
            "(grumpycat)"
         ]
      },
      {
         "filename":"gtfo.png",
         "textCodes":[
            "(gtfo)",
            "(huh)"
         ]
      },
      {
         "filename":"happytear.gif",
         "textCodes":[
            ":')"
         ]
      },
      {
         "filename":"haveaseat.png",
         "textCodes":[
            "(haveaseat)"
         ]
      },
      {
         "filename":"heart.png",
         "textCodes":[
            "(heart)"
         ]
      },
      {
         "filename":"hipchat.png",
         "textCodes":[
            "(hipchat)"
         ]
      },
      {
         "filename":"hipster.png",
         "textCodes":[
            "(hipster)"
         ]
      },
      {
         "filename":"ilied.png",
         "textCodes":[
            "(ilied)"
         ]
      },
      {
         "filename":"indeed.png",
         "textCodes":[
            "(indeed)"
         ]
      },
      {
         "filename":"innocent.png",
         "textCodes":[
            "O:)"
         ]
      },
      {
         "filename":"iseewhatyoudidthere-1348262983.png",
         "textCodes":[
            "(iseewhatyoudidthere)"
         ]
      },
      {
         "filename":"itsatrap.png",
         "textCodes":[
            "(itsatrap)"
         ]
      },
      {
         "filename":"jackie.png",
         "textCodes":[
            "(jackie)"
         ]
      },
      {
         "filename":"jira-1350074257.png",
         "textCodes":[
            "(jira)"
         ]
      },
      {
         "filename":"jobs.png",
         "textCodes":[
            "(jobs)"
         ]
      },
      {
         "filename":"kennypowers.png",
         "textCodes":[
            "(kennypowers)"
         ]
      },
      {
         "filename":"kiss.png",
         "textCodes":[
            ":-*"
         ]
      },
      {
         "filename":"krang.gif",
         "textCodes":[
            "(krang)"
         ]
      },
      {
         "filename":"kwanzaa.png",
         "textCodes":[
            "(kwanzaa)"
         ]
      },
      {
         "filename":"lincoln.png",
         "textCodes":[
            "(lincoln)"
         ]
      },
      {
         "filename":"lol.png",
         "textCodes":[
            "(lol)"
         ]
      },
      {
         "filename":"lolwut.png",
         "textCodes":[
            "(lolwut)"
         ]
      },
      {
         "filename":"megusta.png",
         "textCodes":[
            "(megusta)"
         ]
      },
      {
         "filename":"menorah.png",
         "textCodes":[
            "(menorah)"
         ]
      },
      {
         "filename":"mike.png",
         "textCodes":[
            "(arrington)"
         ]
      },
      {
         "filename":"mindblown-1374883007.gif",
         "textCodes":[
            "(mindblown)"
         ]
      },
      {
         "filename":"moneymouth.png",
         "textCodes":[
            ":$"
         ]
      },
      {
         "filename":"ninja.png",
         "textCodes":[
            "(ninja)"
         ]
      },
      {
         "filename":"notbad.png",
         "textCodes":[
            "(notbad)"
         ]
      },
      {
         "filename":"nothingtodohere.png",
         "textCodes":[
            "(nothingtodohere)"
         ]
      },
      {
         "filename":"notsureif-1342015652.png",
         "textCodes":[
            "(notsureif)"
         ]
      },
      {
         "filename":"notsureifgusta-1346093311.png",
         "textCodes":[
            "(notsureifgusta)"
         ]
      },
      {
         "filename":"obama-1352231289.png",
         "textCodes":[
            "(obama)"
         ]
      },
      {
         "filename":"ohcrap.png",
         "textCodes":[
            "(ohcrap)"
         ]
      },
      {
         "filename":"ohgodwhy.jpeg",
         "textCodes":[
            "(ohgodwhy)"
         ]
      },
      {
         "filename":"okay.png",
         "textCodes":[
            "(okay)"
         ]
      },
      {
         "filename":"omg.png",
         "textCodes":[
            "(omg)"
         ]
      },
      {
         "filename":"oops.png",
         "textCodes":[
            "(oops)"
         ]
      },
      {
         "filename":"orly.png",
         "textCodes":[
            "(orly)"
         ]
      },
      {
         "filename":"pbr.png",
         "textCodes":[
            "(pbr)"
         ]
      },
      {
         "filename":"pete.png",
         "textCodes":[
            "(pete)"
         ]
      },
      {
         "filename":"philosoraptor.png",
         "textCodes":[
            "(philosoraptor)"
         ]
      },
      {
         "filename":"pingpong.png",
         "textCodes":[
            "(pingpong)"
         ]
      },
      {
         "filename":"pirate.gif",
         "textCodes":[
            "(pirate)"
         ]
      },
      {
         "filename":"pokerface.png",
         "textCodes":[
            "(pokerface)"
         ]
      },
      {
         "filename":"poo.png",
         "textCodes":[
            "(poo)"
         ]
      },
      {
         "filename":"present.png",
         "textCodes":[
            "(present)"
         ]
      },
      {
         "filename":"pumpkin.png",
         "textCodes":[
            "(pumpkin)"
         ]
      },
      {
         "filename":"rageguy.png",
         "textCodes":[
            "(rageguy)",
            "(fu)"
         ]
      },
      {
         "filename":"rebeccablack.png",
         "textCodes":[
            "(rebeccablack)"
         ]
      },
      {
         "filename":"reddit.png",
         "textCodes":[
            "(reddit)"
         ]
      },
      {
         "filename":"romney-1352231355.png",
         "textCodes":[
            "(romney)"
         ]
      },
      {
         "filename":"rudolph.png",
         "textCodes":[
            "(rudolph)"
         ]
      },
      {
         "filename":"sadpanda.png",
         "textCodes":[
            "(sadpanda)"
         ]
      },
      {
         "filename":"sadtroll.png",
         "textCodes":[
            "(sadtroll)"
         ]
      },
      {
         "filename":"samuel.png",
         "textCodes":[
            "(samuel)"
         ]
      },
      {
         "filename":"santa.png",
         "textCodes":[
            "(santa)"
         ]
      },
      {
         "filename":"scumbag.png",
         "textCodes":[
            "(scumbag)"
         ]
      },
      {
         "filename":"sealed.png",
         "textCodes":[
            ":Z"
         ]
      },
      {
         "filename":"seomoz.png",
         "textCodes":[
            "(seomoz)"
         ]
      },
      {
         "filename":"shamrock.png",
         "textCodes":[
            "(shamrock)"
         ]
      },
      {
         "filename":"shrug-1349463255.png",
         "textCodes":[
            "(shrug)"
         ]
      },
      {
         "filename":"skyrim.png",
         "textCodes":[
            "(skyrim)"
         ]
      },
      {
         "filename":"slant.png",
         "textCodes":[
            ":\\"
         ]
      },
      {
         "filename":"smile.png",
         "textCodes":[
            ":)",
            ":-)",
            "=)"
         ]
      },
      {
         "filename":"stare.png",
         "textCodes":[
            "(stare)"
         ]
      },
      {
         "filename":"straightface.png",
         "textCodes":[
            ":|"
         ]
      },
      {
         "filename":"success-1348262443.png",
         "textCodes":[
            "(success)"
         ]
      },
      {
         "filename":"successful-1369948592.png",
         "textCodes":[
            "(successful)"
         ]
      },
      {
         "filename":"sweetjesus.png",
         "textCodes":[
            "(sweetjesus)"
         ]
      },
      {
         "filename":"tableflip-1349463264.png",
         "textCodes":[
            "(tableflip)"
         ]
      },
      {
         "filename":"taft.png",
         "textCodes":[
            "(taft)"
         ]
      },
      {
         "filename":"tea.png",
         "textCodes":[
            "(tea)"
         ]
      },
      {
         "filename":"thumbs_down.png",
         "textCodes":[
            "(thumbsdown)"
         ]
      },
      {
         "filename":"thumbs_up.png",
         "textCodes":[
            "(thumbsup)"
         ]
      },
      {
         "filename":"tongue.png",
         "textCodes":[
            ":p"
         ]
      },
      {
         "filename":"tree.png",
         "textCodes":[
            "(tree)"
         ]
      },
      {
         "filename":"troll.png",
         "textCodes":[
            "(troll)"
         ]
      },
      {
         "filename":"truestory.png",
         "textCodes":[
            "(truestory)"
         ]
      },
      {
         "filename":"trump-1352738237.png",
         "textCodes":[
            "(trump)"
         ]
      },
      {
         "filename":"turkey.png",
         "textCodes":[
            "(turkey)"
         ]
      },
      {
         "filename":"twss-1348262400.png",
         "textCodes":[
            "(twss)"
         ]
      },
      {
         "filename":"unknown-1369948620.png",
         "textCodes":[
            "(unknown)"
         ]
      },
      {
         "filename":"washington.png",
         "textCodes":[
            "(washington)"
         ]
      },
      {
         "filename":"wat.png",
         "textCodes":[
            "(wat)"
         ]
      },
      {
         "filename":"wink.png",
         "textCodes":[
            ";)"
         ]
      },
      {
         "filename":"winktongue.gif",
         "textCodes":[
            ";p"
         ]
      },
      {
         "filename":"wtf.png",
         "textCodes":[
            "(wtf)"
         ]
      },
      {
         "filename":"yey.png",
         "textCodes":[
            "(yey)"
         ]
      },
      {
         "filename":"yodawg.png",
         "textCodes":[
            "yodawg.png"
         ]
      },
      {
         "filename":"yougotitdude-1368219664.gif",
         "textCodes":[
            "(yougotitdude)"
         ]
      },
      {
         "filename":"yuno.png",
         "textCodes":[
            "(yuno)"
         ]
      },
      {
         "filename":"zoidberg.png",
         "textCodes":[
            "(zoidberg)"
         ]
      },
      {
         "filename":"zzz.gif",
         "textCodes":[
            "(zzz)"
         ]
      }
   ]
}